-- PALANOTO-MUSICPEDIA-DDL
DROP TABLE IF EXISTS `TB_MUSICPEDIA_RANK`;
DROP TABLE IF EXISTS `TB_MUSICPEDIA_SONG`;
DROP TABLE IF EXISTS `TB_MUSICPEDIA_ARTIST`;

-- ##################################################################################################################
-- 													   TABLE
-- ##################################################################################################################

-- USER
CREATE TABLE IF NOT EXISTS `TB_MUSICPEDIA_SONG` (
	`SONG_ID` VARCHAR(50) NOT NULL,
	`SONG_NAME` VARCHAR(100) NOT NULL,
	`ARTIST_ID` VARCHAR(50) NOT NULL,
	`LYRICS` VARCHAR(3000),
	PRIMARY KEY(`SONG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;

-- ROLE
CREATE TABLE IF NOT EXISTS `TB_MUSICPEDIA_ARTIST` (
	`ARTIST_ID` VARCHAR(50) NOT NULL,
	`ARTIST_NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ARTIST_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `TB_MUSICPEDIA_RANK` (
	`RANK` INT NOT NULL,
	`RANK_DATE` DATE DEFAULT NOW(),
	`SONG_ID` VARCHAR(50) NOT NULL,
	PRIMARY KEY(`SONG_ID`),
	CONSTRAINT `CK_MUSICPEDIA_RANK_RANK` CHECK(RANK BETWEEN 1 AND 100)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;

-- ##################################################################################################################
-- 													   CONSTRAINT
-- ##################################################################################################################

ALTER TABLE `TB_MUSICPEDIA_SONG` ADD CONSTRAINT `FK_MUSICPEDIA_SONG_ARTIST` FOREIGN KEY(`ARTIST_ID`) REFERENCES TB_MUSICPEDIA_ARTIST(`ARTIST_ID`) ON DELETE CASCADE;
ALTER TABLE `TB_MUSICPEDIA_RANK` ADD CONSTRAINT `FK_MUSICPEDIA_RANK` FOREIGN KEY(`SONG_ID`) REFERENCES TB_MUSICPEDIA_SONG(`SONG_ID`) ON DELETE CASCADE;



