# application.yml

server:
# Server Port
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local

#Encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ANSI
  output.ansi.enabled: always

# Import Config
  config:
    import: classpath:/palanoto.yml

# Devtools
  devtools:
    restart:
      enabled: true
#    livereload:
#      enabled: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging
logging:
  level:
    root: error
    com.joje.palanoto: debug

# JWT
jwt:
  header: Authorization
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  token-validity-in-seconds: 1800

---
# Local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4406/palanoto?characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(0/cMqN7QTjW4EQuz4sraGg==)
    password: ENC(n9rDws6yHK8quZHqh6O2K3O/YjkiKP5z)