# application.yml

server:
# Server Port
  port: 9090
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local

# Import Config
  config:
    import: classpath:/palanoto.yml

# Devtools
  devtools:
    restart:
      enabled: true
#    livereload:
#      enabled: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true


---
# Local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4406/palanoto?characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(0/cMqN7QTjW4EQuz4sraGg==)
    password: ENC(n9rDws6yHK8quZHqh6O2K3O/YjkiKP5z)